apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  ports:
  - name: port
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: etcd-k8s
  labels:
    k8s-app: etcd
    namespace: kube-system
subsets:
- addresses:
  - ip: 10.0.2.15
  ports:
  - name: port
    port: 2379
    protocol: TCP