apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: generic-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: generic-exporter
    spec:
      containers:
      - image: generic-exporter:dev
        name: generic-exporter
        ports:
        - containerPort: 10082
        resources:
          requests:
            memory: 20Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
