apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: generic-exporter
  namespace: monitoring
  labels:
    k8s-app: generic-exporter
spec:
  jobLabel: k8s-app
  endpoints:
  - port: port
    interval: 30s
    scheme: http
  selector:
    matchLabels:
      k8s-app: generic-exporter